name: pathmnist
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy=1.23.5
  - tensorflow=2.8.0
  - scikit-learn
  - pandas
  - matplotlib
  - seaborn
  - pip
  - pip:
    - pillow==9.0.0 